{% set data = load_setup_py_data() %}

package:
  name: mapped
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python >=3.7
    - matplotlib >=3.0
    - geopandas >=0.5
    - contextily >=1.0
    - appdirs
    - joblib
    - requests
    - plotly >=4.1
  test:
    - pytest

about:
  home: https://github.com/jpn--/mapped
  license: GPLv3
  license_file: LICENSE
  