package:
  name: mapped
  version: "19.5"

source:
# git_rev: v19.5
# git_url: https://github.com/jpn--/mapped.git
  path: ../

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.7
    - matplotlib >=3.0
    - geopandas >=0.5
    - contextily
    - appdirs
    - joblib
    - requests
  test:
    - pytest

about:
  home: https://github.com/jpn--/mapped
  license: GPLv3
  license_file: LICENSE
  